Multi diag tools: Mdt::ErrorLogger::Logger Class Reference
Mdt::ErrorLogger::Logger Class Reference
Helper class to log Error objects.
#include <Logger.h>
Public Member Functions
Logger (const Logger &)=delete
Logger (Logger &&)=delete
Logger & operator= (const Logger &)=delete
Logger & operator= (Logger &&)=delete
Static Public Member Functions
static void addBackend (const std::shared_ptr< Backend > &backend)
Add a logger backend.
static void logError (const Error &error)
Log given error.
static void cleanup ()
Cleanup.
Detailed Description
Helper class to log Error objects.
Definition at line 40 of file Logger.h.
Member Function Documentation
void Mdt::ErrorLogger::Logger::addBackend (const std::shared_ptr< Backend > & backend) static
Add a logger backend.
Definition at line 27 of file Logger.cpp.
Referenced by Mdt::CoreApplicationImpl::commonEnvironmentEntries(), and Mdt::CoreApplicationImpl::enableFileLogging().
void Mdt::ErrorLogger::Logger::cleanup () static
Cleanup.
Note
This function must be called before returning from main(). Not doing so conducts to undefined behaviour. Consider using a LoggerGuard.
Definition at line 39 of file Logger.cpp.
References Mdt::Error::isNull().
Referenced by Mdt::CoreApplicationImpl::~CoreApplicationImpl(), and Mdt::ErrorLogger::LoggerGuard::~LoggerGuard().
void Mdt::ErrorLogger::Logger::logError (const Error & error) static
Log given error.
This function is thread safe
Precondition
error must not be null
Definition at line 33 of file Logger.cpp.
References Mdt::Error::isNull().
Referenced by Mdt::Error::commit().
The documentation for this class was generated from the following files:
libs/Error_Core/src/Mdt/ErrorLogger/Logger.h
libs/Error_Core/src/Mdt/ErrorLogger/Logger.cpp