Multi diag tools: Mdt::CoreApplicationImpl Class Reference
Mdt::CoreApplicationImpl Class Reference
Implementation for CoreApplication and derived classes.
#include <CoreApplicationImpl.h>
Public Types
enum LogFileNameFormat { ApplicationName, ApplicationNameAndPid }
Log file name format.
Public Member Functions
CoreApplicationImpl ()
Constructor.
~CoreApplicationImpl ()
Destructor.
CoreApplicationImpl (const CoreApplicationImpl &)=delete
CoreApplicationImpl & operator= (const CoreApplicationImpl &)=delete
CoreApplicationImpl (CoreApplicationImpl &&)=delete
CoreApplicationImpl & operator= (CoreApplicationImpl &&)=delete
void enableFileLogging (LogFileNameFormat format)
Enable file logging.
bool isFileLoggingEnabled () const
Check if file logging is enabled.
QString logFilePath ()
Get the path to the log file.
void debugEnvironment (const QStringList &entries)
Debug environment.
QStringList commonEnvironmentEntries ()
Get common environment entries.
Static Public Member Functions
static QString logDirectoryPath ()
Get the path to log file directory.
static QString cacheDirectoryPath ()
Get path to the cache directory.
static QString qtVersion ()
Get Qt library version.
static QString mdtVersion ()
Get Mdt library version.
Detailed Description
Implementation for CoreApplication and derived classes.
Definition at line 33 of file CoreApplicationImpl.h.
Member Enumeration Documentation
enum Mdt::CoreApplicationImpl::LogFileNameFormat
Log file name format.
Enumerator
ApplicationName
Log file name will be applicationName.log
ApplicationNameAndPid
Log file name will be applicationName_pid.log
Definition at line 41 of file CoreApplicationImpl.h.
Constructor & Destructor Documentation
Mdt::CoreApplicationImpl::CoreApplicationImpl ()
Constructor.
Definition at line 38 of file CoreApplicationImpl.cpp.
Mdt::CoreApplicationImpl::~CoreApplicationImpl ()
Destructor.
Definition at line 44 of file CoreApplicationImpl.cpp.
References Mdt::ErrorLogger::Logger::cleanup().
Member Function Documentation
static QString Mdt::CoreApplicationImpl::cacheDirectoryPath () inline static
Get path to the cache directory.
Returns StandardPaths::cacheDirectoryPath()
Definition at line 93 of file CoreApplicationImpl.h.
References Mdt::StandardPaths::cacheDirectoryPath(), commonEnvironmentEntries(), debugEnvironment(), mdtVersion(), and qtVersion().
Referenced by Mdt::CoreApplication::cacheDirectoryPath(), and commonEnvironmentEntries().
QStringList Mdt::CoreApplicationImpl::commonEnvironmentEntries ()
Get common environment entries.
Definition at line 104 of file CoreApplicationImpl.cpp.
References Mdt::ErrorLogger::Logger::addBackend(), cacheDirectoryPath(), logDirectoryPath(), logFilePath(), mdtVersion(), and qtVersion().
Referenced by cacheDirectoryPath().
void Mdt::CoreApplicationImpl::debugEnvironment (const QStringList & entries)
Debug environment.
Definition at line 93 of file CoreApplicationImpl.cpp.
Referenced by cacheDirectoryPath().
void Mdt::CoreApplicationImpl::enableFileLogging (CoreApplicationImpl::LogFileNameFormat format)
Enable file logging.
Definition at line 49 of file CoreApplicationImpl.cpp.
References Mdt::ErrorLogger::Logger::addBackend(), ApplicationName, ApplicationNameAndPid, isFileLoggingEnabled(), and logDirectoryPath().
bool Mdt::CoreApplicationImpl::isFileLoggingEnabled () const inline
Check if file logging is enabled.
Definition at line 68 of file CoreApplicationImpl.h.
Referenced by enableFileLogging().
static QString Mdt::CoreApplicationImpl::logDirectoryPath () inline static
Get the path to log file directory.
Returns StandardPaths::logDirectoryPath()
Definition at line 77 of file CoreApplicationImpl.h.
References Mdt::StandardPaths::logDirectoryPath().
Referenced by commonEnvironmentEntries(), and enableFileLogging().
QString Mdt::CoreApplicationImpl::logFilePath () inline
Get the path to the log file.
Definition at line 84 of file CoreApplicationImpl.h.
Referenced by commonEnvironmentEntries().
QString Mdt::CoreApplicationImpl::mdtVersion () static
Get Mdt library version.
Definition at line 88 of file CoreApplicationImpl.cpp.
Referenced by cacheDirectoryPath(), commonEnvironmentEntries(), and Mdt::CoreApplication::mdtVersion().
QString Mdt::CoreApplicationImpl::qtVersion () static
Get Qt library version.
Definition at line 83 of file CoreApplicationImpl.cpp.
Referenced by cacheDirectoryPath(), commonEnvironmentEntries(), and Mdt::CoreApplication::qtVersion().
The documentation for this class was generated from the following files:
libs/Application_Core/src/Mdt/CoreApplicationImpl.h
libs/Application_Core/src/Mdt/CoreApplicationImpl.cpp