Multi diag tools: Mdt::ErrorLogger::FileBackend Class Reference
Mdt::ErrorLogger::FileBackend Class Reference
File backend for error Logger.
#include <FileBackend.h>
Public Member Functions
FileBackend ()
Constructor.
~FileBackend ()
Destructor.
bool setLogFilePath (const QString &path, qint64 maxFileSize=1024 *1024)
Set path to log file.
QString logFilePath () const
Get log file path.
QString backupLogFilePath () const
Get backup log file path.
qint64 maxFileSize () const
Get maximum log file size.
void logError (const Error &error)
Log given error.
Public Member Functions inherited from Mdt::ErrorLogger::Backend
Backend ()
Constructor.
virtual ~Backend ()
Destructor.
Backend (const Backend &)=delete
Backend (Backend &&)=delete
Backend & operator= (const Backend &)=delete
Backend & operator= (Backend &&)=delete
Additional Inherited Members
Static Protected Member Functions inherited from Mdt::ErrorLogger::Backend
static QString tr (const char *text)
Calls QObject::tr()
Detailed Description
File backend for error Logger.
Definition at line 34 of file FileBackend.h.
Constructor & Destructor Documentation
Mdt::ErrorLogger::FileBackend::FileBackend ()
Constructor.
Definition at line 32 of file FileBackend.cpp.
Mdt::ErrorLogger::FileBackend::~FileBackend ()
Destructor.
Definition at line 37 of file FileBackend.cpp.
Member Function Documentation
QString Mdt::ErrorLogger::FileBackend::backupLogFilePath () const
Get backup log file path.
Definition at line 64 of file FileBackend.cpp.
void Mdt::ErrorLogger::FileBackend::logError (const Error & error) virtual
Log given error.
Implements Mdt::ErrorLogger::Backend.
Definition at line 74 of file FileBackend.cpp.
References Mdt::Error::Critical, Mdt::Error::fileLine(), Mdt::Error::fileName(), Mdt::Error::functionName(), Mdt::Error::getErrorStack(), Mdt::Error::Info, Mdt::Error::informativeText(), Mdt::Error::level(), Mdt::Error::NoError, Mdt::Error::text(), Mdt::ErrorLogger::Backend::tr(), and Mdt::Error::Warning.
QString Mdt::ErrorLogger::FileBackend::logFilePath () const
Get log file path.
Definition at line 59 of file FileBackend.cpp.
qint64 Mdt::ErrorLogger::FileBackend::maxFileSize () const
Get maximum log file size.
Definition at line 69 of file FileBackend.cpp.
Referenced by setLogFilePath().
bool Mdt::ErrorLogger::FileBackend::setLogFilePath (const QString & path, qint64 maxFileSize = 1024*1024)
Set path to log file.
Parameters
path Path to the log file. Note that a backup is made in same directory than file given by path, with a other exention.
maxFileSize Maximum size allowed for log file [Byte] Also note that the file can be some bytes greater than specified size.
Note
This function should only be called before this LoggerFileBackend is passed to the Logger (changing file path while Logger is calling logError() is undefined behaviour).
Definition at line 41 of file FileBackend.cpp.
References maxFileSize(), and Mdt::ErrorLogger::Backend::tr().
The documentation for this class was generated from the following files:
libs/Error_Core/src/Mdt/ErrorLogger/FileBackend.h
libs/Error_Core/src/Mdt/ErrorLogger/FileBackend.cpp